"""Add is_active and linked_status

Revision ID: 2b23a9eb81fc
Revises: af10146bfada
Create Date: 2026-03-20 22:05:10.686853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b23a9eb81fc'
down_revision = 'af10146bfada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('linked_status', sa.String(length=256), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('linked_status', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('linked_status')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_column('linked_status')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
