"""add user model
Revision ID: af10146bfada
Revises: f86a70184d27
Create Date: 2026-03-20 19:13:54.668652
"""
from alembic import op
import sqlalchemy as sa
# revision identifiers, used by Alembic.
revision = 'af10146bfada'
down_revision = 'f86a70184d27'
branch_labels = None
depends_on = None
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
    with op.batch_alter_table('care_coordinator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_coordinator_email'))
        batch_op.drop_index(batch_op.f('ix_care_coordinator_name'))
        batch_op.create_foreign_key('fk_care_coordinator_user', 'user', ['id'], ['id'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_email'))
        batch_op.drop_index(batch_op.f('ix_doctor_name'))
        batch_op.create_foreign_key('fk_doctor_user', 'user', ['id'], ['id'])
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')
        batch_op.drop_column('name')
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_email'))
        batch_op.drop_index(batch_op.f('ix_volunteer_name'))
        batch_op.create_foreign_key('fk_volunteer_user', 'user', ['id'], ['id'])
        batch_op.drop_column('email')
        batch_op.drop_column('name')
        batch_op.drop_column('password_hash')
    # ### end Alembic commands ###
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint('fk_volunteer_user', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_volunteer_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ix_volunteer_email'), ['email'], unique=1)
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint('fk_doctor_user', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_doctor_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ix_doctor_email'), ['email'], unique=1)
    with op.batch_alter_table('care_coordinator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
        batch_op.drop_constraint('fk_care_coordinator_user', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_care_coordinator_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ix_care_coordinator_email'), ['email'], unique=1)
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
    op.drop_table('user')
    # ### end Alembic commands ###
