"""initial migration

Revision ID: f86a70184d27
Revises: 
Create Date: 2026-03-20 18:59:47.328416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f86a70184d27'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_coordinator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('facility_programs', sa.String(length=256), nullable=True),
    sa.Column('shift_requirements', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('care_coordinator', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_care_coordinator_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_care_coordinator_name'), ['name'], unique=True)

    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('specialty', sa.String(length=128), nullable=True),
    sa.Column('current_projects', sa.String(length=512), nullable=True),
    sa.Column('required_skills', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctor_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_doctor_name'), ['name'], unique=True)

    op.create_table('resident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('life_history', sa.String(length=512), nullable=True),
    sa.Column('hobbies', sa.String(length=256), nullable=True),
    sa.Column('cognitive_profile', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resident_name'), ['name'], unique=True)

    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('major', sa.String(length=64), nullable=True),
    sa.Column('minor', sa.String(length=64), nullable=True),
    sa.Column('year_of_study', sa.String(length=64), nullable=True),
    sa.Column('career_goals', sa.String(length=256), nullable=True),
    sa.Column('skills', sa.String(length=256), nullable=True),
    sa.Column('interest_keywords', sa.String(length=256), nullable=True),
    sa.Column('availability', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_volunteer_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_name'))
        batch_op.drop_index(batch_op.f('ix_volunteer_email'))

    op.drop_table('volunteer')
    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resident_name'))

    op.drop_table('resident')
    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctor_name'))
        batch_op.drop_index(batch_op.f('ix_doctor_email'))

    op.drop_table('doctor')
    with op.batch_alter_table('care_coordinator', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_care_coordinator_name'))
        batch_op.drop_index(batch_op.f('ix_care_coordinator_email'))

    op.drop_table('care_coordinator')
    # ### end Alembic commands ###
